import Head from "next/head";
import {
  AiOutlineMail,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Tecnologia from "../public/Tecnologia.png";
import Educacion from "../public/Educacion.png";
import Trabajo from "../public/Trabajo.png";
import Perfil from "../public/Perfil.png";
import Image from "next/image";
import CV from '../public/CV.jpg'


import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-cards";

// import required modules
import { EffectCards } from "swiper";


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Oscar Arregoces</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portafolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  download="CV -  Oscar Arregoces"
                  href='/CV.pdf'
                >
                  
                  Descargar CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Oscar Arregoces
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desarrollador Web
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hola! Tengo 23 años y soy desarrollador Web Full Stack orientado al FontEnd, soy creativo y me gusta aprender cosas nuevas todos los dias.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="mailto:oiarregoces@uniguajira.edu.co"> <AiOutlineMail /> </a>
              <a href="https://www.linkedin.com/in/oscar-arregoces-b61921252" target="_blank" rel="noreferrer"> <AiFillLinkedin /> </a>
              <a href="https://github.com/OscarArregoces" target="_blank" rel="noreferrer"> <AiFillGithub /> </a>


            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 perfil">
              <Image src={Perfil} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Conocemé un poco</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">

            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Estudié ingenieria de sistemas en la universidad de La Guajira y actualmente estoy en terminación academica. Durante mis años universitarios tambien he estudiado de manera autodidacta a traves de contenido virtual en diversas plataformas como Udemy y YouTube, las cuales me ayudarón mucho a complementar mi formacion.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Educación
              </h3>
              <Image src={Educacion} width={100} height={100} />
              <p className="py-2 text-teal-600 text-lg ">
                Ingenierio de sistemas en la Universidad de La Guajira en terminación acadedmica.
              </p>
              <p className="text-gray-800 py-1">Cursos:</p>
              <ul id="ul">
                <li className="text-gray-800 py-1">Udemy - React: De cero a experto ( Hooks y MERN )</li>
                <li className="text-gray-800 py-1">Udemy - React PRO: Lleva tus bases al siguiente nivel</li>
                <li className="text-gray-800 py-1">Udemy - Angular Avanzado: Lleva tus bases al siguiente nivel - MEAN</li>
                <li className="text-gray-800 py-1">Udemy - Build Responsive Real-World Websites with HTML and CSS</li>
                <li className="text-gray-800 py-1">Udemy - Master en JavaScript: Aprender JS, jQuery, Angular, NodeJS</li>
              </ul>
              {/* <h4 className="text-gray-800 py-1">Udemy - React: De cero a experto ( Hooks y MERN )</h4>
              <p className="text-gray-800 py-1">Udemy - React PRO: Lleva tus bases al siguiente nivel</p>
              <p className="text-gray-800 py-1">Udemy - Angular Avanzado: Lleva tus bases al siguiente nivel - MEAN</p>
              <p className="text-gray-800 py-1">Udemy - Build Responsive Real-World Websites with HTML and CSS</p>
              <p className="text-gray-800 py-1">Udemy - Master en JavaScript: Aprender JS, jQuery, Angular, NodeJS</p> */}
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Habilidades
              </h3>
              <Image src={Tecnologia} width={100} height={100} />
              <p className="py-2 text-teal-600 text-lg ">
                Tecnologias:
              </p>
              <ul id="ul">
                <li className="text-gray-800 py-1">JavaScript/TypeScript</li>
                <li className="text-gray-800 py-1">React</li>
                <li className="text-gray-800 py-1">Angular</li>
                <li className="text-gray-800 py-1">Django</li>
                <li className="text-gray-800 py-1">Node Js</li>
                <li className="text-gray-800 py-1">MySql</li>
                <li className="text-gray-800 py-1">Redux</li>
              </ul>

              <p className="py-2 text-teal-600 text-lg ">
                Capacidades:
              </p>
              <ul id="ul">
                <li className="text-gray-800 py-1">Trabajo en equipo</li>
                <li className="text-gray-800 py-1">Capacidad de adaptación</li>
                <li className="text-gray-800 py-1">Comunicación oral</li>
                <li className="text-gray-800 py-1">Creativo</li>
              </ul>
              {/* 
              <h4 className="text-gray-800 py-1">JavaScript/TypeScript</h4>
              <h4 className="text-gray-800 py-1">Redux</h4>
              <h4 className="text-gray-800 py-1">React</h4>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">Node Js</p>
              <p className="text-gray-800 py-1">MySql</p> */}
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">Experiencia</h3>
              <Image src={Trabajo} width={100} height={100} />
              <p className="py-2 text-teal-600 text-lg ">
                Sistema Web responsivo para el seguimiento de los graduados en la Universidad de La Guajira.
              </p>
              <p className="text-gray-800 py-1">Tareas:</p>
              <ul id="ul">
                <li className="text-gray-800 py-1">Realizar la estructura y diseño del software.</li>
                <li className="text-gray-800 py-1">Desarrollar aplicaciones orientadas al usuario y supervisar su eficacia.</li>
                <li className="text-gray-800 py-1">Comprender las necesidades de la empresa y trabajar con el personal pertinente para garantizar la máxima eficacia del software.</li>
                <li className="text-gray-800 py-1">Colaborar con los desarrolladores BackEnd para garantizar que el software funcione de acuerdo con lo definido.</li>
                <li className="text-gray-800 py-1">Cambiar el diseño y el contenido de las páginas existentes en beneficio de los usuarios, clientes y compañeros.</li>
              </ul>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Proyectos</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

            <div className="contenedor-swiper">
              <Swiper
                effect={"cards"}
                grabCursor={true}
                modules={[EffectCards]}
                className="mySwiper"
              >
                <SwiperSlide> <div className="Pokemon1"></div> </SwiperSlide>
                <SwiperSlide> <div className="Pokemon2"></div> </SwiperSlide>
                <SwiperSlide>  <div className="Pokemon3"></div> </SwiperSlide>
              </Swiper>
              <h3 className="text-lg font-medium pt-8 pb-2">Pokedex</h3>
            </div>
            <div className="contenedor-swiper">
              <Swiper
                effect={"cards"}
                grabCursor={true}
                modules={[EffectCards]}
                className="mySwiper"
              >
                <SwiperSlide> <div className="Gimnasio1"></div> </SwiperSlide>
                <SwiperSlide> <div className="Gimnasio2"></div> </SwiperSlide>
                <SwiperSlide> <div className="Gimnasio3"></div> </SwiperSlide>
              </Swiper>
              <h3 className="text-lg font-medium pt-8 pb-2">Software de gimnasio</h3>
            </div>
            <div className="contenedor-swiper">
              <Swiper
                effect={"cards"}
                grabCursor={true}
                modules={[EffectCards]}
                className="mySwiper"
              >
                <SwiperSlide> <div className="Egresado1"></div> </SwiperSlide>
                <SwiperSlide> <div className="Egresado2"></div> </SwiperSlide>
                <SwiperSlide> <div className="Egresado3"></div> </SwiperSlide>
              </Swiper>
              <h3 className="text-lg font-medium pt-8 pb-2"> Software administrativo</h3>
            </div>



            {/* <Swiper
              spaceBetween={30}
              effect={"fade"}
              navigation={true}
              pagination={{
                clickable: true,
              }}
              modules={[EffectFade, Navigation, Pagination]}
              className="mySwiper"
            >
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Pokemon1}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Pokemon2}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Pokemon3}
                />
              </SwiperSlide>
            </Swiper>

            <Swiper
              spaceBetween={30}
              effect={"fade"}
              navigation={true}
              pagination={{
                clickable: true,
              }}
              modules={[EffectFade, Navigation, Pagination]}
              className="mySwiper"
            >
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Gimnasio1}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Gimnasio2}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Gimnasio3}
                />
              </SwiperSlide>
            </Swiper>

            <Swiper
              spaceBetween={30}
              effect={"fade"}
              navigation={true}
              pagination={{
                clickable: true,
              }}
              modules={[EffectFade, Navigation, Pagination]}
              className="mySwiper"
            >
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Egresados1}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Egresados2}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Egresados3}
                />
              </SwiperSlide>
            </Swiper> */}
            {/* <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Pokemon1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Pokemon2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Gimnasio1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Gimnasio3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Egresados1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Egresados2}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
